# --- Dataset ------------------------------------------------------
dataset:
  name: MAMe
  img_size: 256        # Keeps native resolution; stem reduces it to 64×64

# --- Model --------------------------------------------------------
model:
  type: InceptionNet
  training_mode: overfit

  classifier:
    layers:     [32768, 4096]
    dropout:    0.05
    activation: ReLU

  stem_cfg:
    use_bn: false
    init_channels: 64
    kernel_size: 3
    pool_kernel_size: 2
  # ---------------------------------------------------------------
  # Inception stages ≈ GoogLeNet extended with SE + residual
  # ---------------------------------------------------------------
  stages:
    - blocks:
        - b0:        2048
          b1:      [256, 1024]
          b2:      [256, 1024]
          pool_proj: 1024
          use_bn:    false
          use_se:    false
          residual:  false
      downsample: true

    - blocks:
        - b0:        8192
          b1:      [256, 2048]
          b2:      [256, 2048]
          pool_proj: 2048
          use_bn:    false
          use_se:    false
          residual:  false
      downsample: false




augmentations:
  active: false
  resize: [256, 256]
  random_horizontal_flip: true
  random_rotation: 30
  random_resized_crop: [256, 256]
  scale: [0.8, 1.0]
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# --- Training -----------------------------------------------------
training:
  epochs: 300           # Long training for stabilization
  batch_size: 2
  training_mode: search
  patience: 30
  optimizer:
    type: adam 
    params:
      lr: 0.001

  scheduler:
    type: step
    params:
      step_size: 10
      gamma: 0.9
